title: Virender Chaudhary's Blog
tagline: Senior Software Engineer | Architect |C# | .NET | Cloud | Data Pipelines | Docker | K8 | CICD
description: Personal blog sharing knowledge about Software development, Cloud engineering, and software architecture.
url: "https://chaudharyvk.github.io"
baseurl: ""
author:
  name: "Virender Chaudhary"
  email: "ChaudharyVirender@outlook.com"
  github: chaudharyvk
  linkedin:  www.linkedin.com/in/virenderchaudhary

lang: en
timezone: Europe/Berlin

theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
