title: Virender Chaudhary's Blog
tagline: Senior Backend Engineer | .NET | Cloud | Data Pipelines
description: Personal blog sharing knowledge about backend development, cloud engineering, and software architecture.
url: "https://chaudharyvk.github.io"
baseurl: ""
author:
  name: "Virender Chaudhary"
  email: "virender@example.com"
  github: chaudharyvk
  linkedin: virender-chaudhary
  twitter: chaudhary_vk
lang: en
timezone: Europe/Berlin

theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
